
CREATE DATABASE IF NOT EXISTS ecole;

USE ecole;

CREATE TABLE IF NOT EXISTS etudiant (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(30) NOT NULL,
    prenom VARCHAR(30) NOT NULL,
    date_naissance DATE,
    classe VARCHAR(10)
);